### ISSUE TITLE
Reading Report Prompts

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-wi16#18]
@depstein: I remember us brainstorming other prompts how to approach reading reports. But I don't remember them. What did we come up with?

**Comment by depstein** [comment]
I don't remember brainstorming specific prompts so much as discuss the importance of having good ones. After reading yours and the surrounding text, I want to add:
- What aspects of this work were particularly well done or effective?
- If you had conducted this research, what would you have done differently?

This mirrors the text you have in the paragraph above.
