### ISSUE TITLE
Project Websites

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-wi16#2]
Should we require project websites, linked from the course website?

Instead of Canvas submissions of things?

I don't think so. I think it's fine for these projects to be a bit more "in the dark".

If we decide yes, we'll need a way to link them.

**Comment by depstein** [comment]
I expect at least a few instances where students don't want to make their projects public (unpublished research findings, for example). Canvas is probably fine.

**Comment by jayfo** [comment]
Perhaps we end up with somewhere that lists the project names and students.

But yeah, not a complete record.
