### ISSUE TITLE
Pasteur's quadrant reading

### ISSUE THREAD

**Issue by depstein** [uwcse510/web-cse510-wi16#20]
No good public link, Jake scanned pages of the book. But the copy I have from him has his personal highlights.

**Comment by jayfo** [comment]
Is it this?

http://archive.cspo.org/products/conferences/bush/Stokes.pdf

**Comment by depstein** [comment]
That looks like a commentary from the author. It might be okay though... I only skimmed it.

You might be able to see Jake's version by logging in and viewing: https://faculty.washington.edu/wobbrock/teaching/insc570/Stokes-1997.pdf

We read the first few chapters of his book: http://www.amazon.com/Pasteurs-Quadrant-Science-Technological-Innovation/dp/0815781776
