### ISSUE TITLE
Readings folder isn't publishing

### ISSUE THREAD

**Issue by depstein** [uwcse510/web-cse510-wi16#28]
Doesn't resolve: https://courses.cs.washington.edu/readings/weiser_21st_century.pdf
Neither does: https://courses.cs.washington.edu/readings/stokes_pasteurs_quadrant.pdf

Both are on the repo, though.

Which makes me wonder whether those shouldn't be on the repo...? Should they not be publicly accessible?

**Comment by jayfo** [comment]
It's publishing. You just haven't been putting a `{{ site.baseurl }}` on the front of your internal links.

I'll fix those three, as I'm adding other papers.
