### ISSUE TITLE
Add links/affiliations for guests?

### ISSUE THREAD

**Issue by depstein** [uwcse510/web-cse510-wi16#55]
Not sold on the idea, but not everyone knows who Kurtis/Andy/Jake are.

**Comment by jayfo** [comment]
Yeah, I was thinking we should do this.

**Comment by depstein** [comment]
Ok, I'll put together a pull request.

**Comment by depstein** [comment]
Just links, or also affiliations? Is Kurtis UW CSE, Endaga, or Berkeley?

**Comment by jayfo** [comment]
Let's just do links, to avoid needing to resolve that question.
