### ISSUE TITLE
Post Katharina Instance Papers

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-wi16#81]
Katharina Reinecke, David Flatla, and Christopher Brooks, "Enabling Designers to Foresee Which Colors Users Cannot See", Human Factors in Computing Systems (CHI), 2016 (to appear). Acceptance: 23.4% 

https://homes.cs.washington.edu/~reinecke/Publications_files/ReineckeCHI2016.pdf

Carol Moser, Sarita Yardi Schoenebeck, and Katharina Reinecke, "Technology at the Table: Attitudes about Mobile Phone Use at Mealtimes", Human Factors in Computing Systems (CHI), 2016 (to appear). Acceptance: 23.4% 

https://homes.cs.washington.edu/~reinecke/Publications_files/MoserCHI2016.pdf

**Comment by depstein** [comment]
Should I make local copies, or link to hers?

~Daniel Epstein

**Comment by jayfo** [comment]
Might as well go local, to be consistent with what we've been doing.
